name: Deploy Learn Platform

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: "latest"

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Configure kubectl
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Add CloudNativePG Helm Repo
        run: |
          helm repo add cnpg https://cloudnative-pg.github.io/charts
          helm repo update

      - name: Install CloudNativePG Operator
        run: |
          helm upgrade --install cnpg cnpg/cloudnative-pg \
            --namespace cnpg-system \
            --create-namespace \
            --wait

      - name: Create Namespace
        run: |
          kubectl create namespace learn-platform --dry-run=client -o yaml | kubectl apply -f -

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/catalinpit/learn-platform:${{ github.sha }}
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Learn Platform
        run: |
          helm upgrade --install learn-platform . \
            --namespace learn-platform \
            --set image.tag=${{ github.sha }} \
            --set ingress.hosts[0].host=${{ secrets.DOMAIN }}
