/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UnverifiedImport } from './routes/unverified'
import { Route as SignoutImport } from './routes/signout'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as AboutImport } from './routes/about'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as CoursesCourseIdImport } from './routes/courses/$courseId'
import { Route as AuthenticatedSettingsIndexImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedCreatorNewCourseImport } from './routes/_authenticated/creator/new-course'
import { Route as AuthenticatedCreatorDashboardImport } from './routes/_authenticated/creator/dashboard'
import { Route as AuthenticatedCreatorCoursesImport } from './routes/_authenticated/creator/courses'
import { Route as AuthenticatedStudentCoursesIndexImport } from './routes/_authenticated/student/courses/index'
import { Route as AuthenticatedCreatorCourseIdEditImport } from './routes/_authenticated/creator/$courseId.edit'
import { Route as AuthenticatedStudentCoursesCourseIdIndexImport } from './routes/_authenticated/student/courses/$courseId/index'
import { Route as AuthenticatedStudentCoursesCourseIdLessonsLessonIdImport } from './routes/_authenticated/student/courses/$courseId/lessons/$lessonId'

// Create/Update Routes

const UnverifiedRoute = UnverifiedImport.update({
  id: '/unverified',
  path: '/unverified',
  getParentRoute: () => rootRoute,
} as any)

const SignoutRoute = SignoutImport.update({
  id: '/signout',
  path: '/signout',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CoursesCourseIdRoute = CoursesCourseIdImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedSettingsIndexRoute = AuthenticatedSettingsIndexImport.update(
  {
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
)

const AuthenticatedCreatorNewCourseRoute =
  AuthenticatedCreatorNewCourseImport.update({
    id: '/creator/new-course',
    path: '/creator/new-course',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedCreatorDashboardRoute =
  AuthenticatedCreatorDashboardImport.update({
    id: '/creator/dashboard',
    path: '/creator/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedCreatorCoursesRoute =
  AuthenticatedCreatorCoursesImport.update({
    id: '/creator/courses',
    path: '/creator/courses',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedStudentCoursesIndexRoute =
  AuthenticatedStudentCoursesIndexImport.update({
    id: '/student/courses/',
    path: '/student/courses/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedCreatorCourseIdEditRoute =
  AuthenticatedCreatorCourseIdEditImport.update({
    id: '/creator/$courseId/edit',
    path: '/creator/$courseId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedStudentCoursesCourseIdIndexRoute =
  AuthenticatedStudentCoursesCourseIdIndexImport.update({
    id: '/student/courses/$courseId/',
    path: '/student/courses/$courseId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedStudentCoursesCourseIdLessonsLessonIdRoute =
  AuthenticatedStudentCoursesCourseIdLessonsLessonIdImport.update({
    id: '/student/courses/$courseId/lessons/$lessonId',
    path: '/student/courses/$courseId/lessons/$lessonId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/signout': {
      id: '/signout'
      path: '/signout'
      fullPath: '/signout'
      preLoaderRoute: typeof SignoutImport
      parentRoute: typeof rootRoute
    }
    '/unverified': {
      id: '/unverified'
      path: '/unverified'
      fullPath: '/unverified'
      preLoaderRoute: typeof UnverifiedImport
      parentRoute: typeof rootRoute
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/creator/courses': {
      id: '/_authenticated/creator/courses'
      path: '/creator/courses'
      fullPath: '/creator/courses'
      preLoaderRoute: typeof AuthenticatedCreatorCoursesImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/creator/dashboard': {
      id: '/_authenticated/creator/dashboard'
      path: '/creator/dashboard'
      fullPath: '/creator/dashboard'
      preLoaderRoute: typeof AuthenticatedCreatorDashboardImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/creator/new-course': {
      id: '/_authenticated/creator/new-course'
      path: '/creator/new-course'
      fullPath: '/creator/new-course'
      preLoaderRoute: typeof AuthenticatedCreatorNewCourseImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/creator/$courseId/edit': {
      id: '/_authenticated/creator/$courseId/edit'
      path: '/creator/$courseId/edit'
      fullPath: '/creator/$courseId/edit'
      preLoaderRoute: typeof AuthenticatedCreatorCourseIdEditImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/student/courses/': {
      id: '/_authenticated/student/courses/'
      path: '/student/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof AuthenticatedStudentCoursesIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/student/courses/$courseId/': {
      id: '/_authenticated/student/courses/$courseId/'
      path: '/student/courses/$courseId'
      fullPath: '/student/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedStudentCoursesCourseIdIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/student/courses/$courseId/lessons/$lessonId': {
      id: '/_authenticated/student/courses/$courseId/lessons/$lessonId'
      path: '/student/courses/$courseId/lessons/$lessonId'
      fullPath: '/student/courses/$courseId/lessons/$lessonId'
      preLoaderRoute: typeof AuthenticatedStudentCoursesCourseIdLessonsLessonIdImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedCreatorCoursesRoute: typeof AuthenticatedCreatorCoursesRoute
  AuthenticatedCreatorDashboardRoute: typeof AuthenticatedCreatorDashboardRoute
  AuthenticatedCreatorNewCourseRoute: typeof AuthenticatedCreatorNewCourseRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedCreatorCourseIdEditRoute: typeof AuthenticatedCreatorCourseIdEditRoute
  AuthenticatedStudentCoursesIndexRoute: typeof AuthenticatedStudentCoursesIndexRoute
  AuthenticatedStudentCoursesCourseIdIndexRoute: typeof AuthenticatedStudentCoursesCourseIdIndexRoute
  AuthenticatedStudentCoursesCourseIdLessonsLessonIdRoute: typeof AuthenticatedStudentCoursesCourseIdLessonsLessonIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCreatorCoursesRoute: AuthenticatedCreatorCoursesRoute,
  AuthenticatedCreatorDashboardRoute: AuthenticatedCreatorDashboardRoute,
  AuthenticatedCreatorNewCourseRoute: AuthenticatedCreatorNewCourseRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedCreatorCourseIdEditRoute: AuthenticatedCreatorCourseIdEditRoute,
  AuthenticatedStudentCoursesIndexRoute: AuthenticatedStudentCoursesIndexRoute,
  AuthenticatedStudentCoursesCourseIdIndexRoute:
    AuthenticatedStudentCoursesCourseIdIndexRoute,
  AuthenticatedStudentCoursesCourseIdLessonsLessonIdRoute:
    AuthenticatedStudentCoursesCourseIdLessonsLessonIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/signout': typeof SignoutRoute
  '/unverified': typeof UnverifiedRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/creator/courses': typeof AuthenticatedCreatorCoursesRoute
  '/creator/dashboard': typeof AuthenticatedCreatorDashboardRoute
  '/creator/new-course': typeof AuthenticatedCreatorNewCourseRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/creator/$courseId/edit': typeof AuthenticatedCreatorCourseIdEditRoute
  '/student/courses': typeof AuthenticatedStudentCoursesIndexRoute
  '/student/courses/$courseId': typeof AuthenticatedStudentCoursesCourseIdIndexRoute
  '/student/courses/$courseId/lessons/$lessonId': typeof AuthenticatedStudentCoursesCourseIdLessonsLessonIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/signout': typeof SignoutRoute
  '/unverified': typeof UnverifiedRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/creator/courses': typeof AuthenticatedCreatorCoursesRoute
  '/creator/dashboard': typeof AuthenticatedCreatorDashboardRoute
  '/creator/new-course': typeof AuthenticatedCreatorNewCourseRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/creator/$courseId/edit': typeof AuthenticatedCreatorCourseIdEditRoute
  '/student/courses': typeof AuthenticatedStudentCoursesIndexRoute
  '/student/courses/$courseId': typeof AuthenticatedStudentCoursesCourseIdIndexRoute
  '/student/courses/$courseId/lessons/$lessonId': typeof AuthenticatedStudentCoursesCourseIdLessonsLessonIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/signout': typeof SignoutRoute
  '/unverified': typeof UnverifiedRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/_authenticated/creator/courses': typeof AuthenticatedCreatorCoursesRoute
  '/_authenticated/creator/dashboard': typeof AuthenticatedCreatorDashboardRoute
  '/_authenticated/creator/new-course': typeof AuthenticatedCreatorNewCourseRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/creator/$courseId/edit': typeof AuthenticatedCreatorCourseIdEditRoute
  '/_authenticated/student/courses/': typeof AuthenticatedStudentCoursesIndexRoute
  '/_authenticated/student/courses/$courseId/': typeof AuthenticatedStudentCoursesCourseIdIndexRoute
  '/_authenticated/student/courses/$courseId/lessons/$lessonId': typeof AuthenticatedStudentCoursesCourseIdLessonsLessonIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/about'
    | '/login'
    | '/register'
    | '/signout'
    | '/unverified'
    | '/courses/$courseId'
    | '/creator/courses'
    | '/creator/dashboard'
    | '/creator/new-course'
    | '/settings'
    | '/creator/$courseId/edit'
    | '/student/courses'
    | '/student/courses/$courseId'
    | '/student/courses/$courseId/lessons/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/about'
    | '/login'
    | '/register'
    | '/signout'
    | '/unverified'
    | '/courses/$courseId'
    | '/creator/courses'
    | '/creator/dashboard'
    | '/creator/new-course'
    | '/settings'
    | '/creator/$courseId/edit'
    | '/student/courses'
    | '/student/courses/$courseId'
    | '/student/courses/$courseId/lessons/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/login'
    | '/register'
    | '/signout'
    | '/unverified'
    | '/courses/$courseId'
    | '/_authenticated/creator/courses'
    | '/_authenticated/creator/dashboard'
    | '/_authenticated/creator/new-course'
    | '/_authenticated/settings/'
    | '/_authenticated/creator/$courseId/edit'
    | '/_authenticated/student/courses/'
    | '/_authenticated/student/courses/$courseId/'
    | '/_authenticated/student/courses/$courseId/lessons/$lessonId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SignoutRoute: typeof SignoutRoute
  UnverifiedRoute: typeof UnverifiedRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SignoutRoute: SignoutRoute,
  UnverifiedRoute: UnverifiedRoute,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/about",
        "/login",
        "/register",
        "/signout",
        "/unverified",
        "/courses/$courseId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/creator/courses",
        "/_authenticated/creator/dashboard",
        "/_authenticated/creator/new-course",
        "/_authenticated/settings/",
        "/_authenticated/creator/$courseId/edit",
        "/_authenticated/student/courses/",
        "/_authenticated/student/courses/$courseId/",
        "/_authenticated/student/courses/$courseId/lessons/$lessonId"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/signout": {
      "filePath": "signout.tsx"
    },
    "/unverified": {
      "filePath": "unverified.tsx"
    },
    "/courses/$courseId": {
      "filePath": "courses/$courseId.tsx"
    },
    "/_authenticated/creator/courses": {
      "filePath": "_authenticated/creator/courses.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/creator/dashboard": {
      "filePath": "_authenticated/creator/dashboard.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/creator/new-course": {
      "filePath": "_authenticated/creator/new-course.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/": {
      "filePath": "_authenticated/settings/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/creator/$courseId/edit": {
      "filePath": "_authenticated/creator/$courseId.edit.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/student/courses/": {
      "filePath": "_authenticated/student/courses/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/student/courses/$courseId/": {
      "filePath": "_authenticated/student/courses/$courseId/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/student/courses/$courseId/lessons/$lessonId": {
      "filePath": "_authenticated/student/courses/$courseId/lessons/$lessonId.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
