services:
  server:
    build:
      context: ../../ # Build from monorepo root
      dockerfile: apps/server/Dockerfile
    ports:
      - "9999:9999"
    depends_on:
      - db
    networks:
      - learn-platform-network
    environment:
      - NODE_ENV=production
      # Add your environment variables here

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - learn-platform-network
    ports:
      - 5432:5432

networks:
  learn-platform-network:
    driver: bridge

volumes:
  postgres-data:
