{{- if .Values.cloudnativepg.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.postgresql.cluster.name }}
  namespace: {{ .Values.postgresql.cluster.namespace }}
  labels:
    {{- include "learn-platform.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.postgresql.cluster.instances }}
  imageName: ghcr.io/cloudnative-pg/postgresql:{{ .Values.postgresql.cluster.postgresql.version }}
  postgresql:
    parameters:
      shared_buffers: {{ .Values.postgresql.cluster.postgresGUC.shared_buffers | quote }}
      max_connections: {{ .Values.postgresql.cluster.postgresGUC.max_connections | quote }}
  storage:
    size: {{ .Values.postgresql.cluster.storage.size }}
  bootstrap:
    initdb:
      database: {{ .Values.postgresql.cluster.bootstrap.initdb.database }}
      owner: {{ .Values.postgresql.cluster.bootstrap.initdb.owner }}
  monitoring:
    enablePodMonitor: {{ .Values.postgresql.cluster.monitoring.enablePodMonitor }}
  resources:
    requests:
      cpu: {{ .Values.postgresql.cluster.resources.requests.cpu | quote }}
      memory: {{ .Values.postgresql.cluster.resources.requests.memory | quote }}
    limits:
      memory: {{ .Values.postgresql.cluster.resources.limits.memory | quote }}
  superuserSecret:
    name: {{ .Values.postgresql.cluster.superuserSecret.name }}
  enableSuperuserAccess: {{ .Values.postgresql.cluster.enableSuperuserAccess }}
{{- end }}
