{{- if and .Values.cloudnativepg.enabled .Values.postgresql.cluster.enableSuperuserAccess }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.cluster.superuserSecret.name }}
  namespace: {{ .Values.postgresql.cluster.namespace }}
  labels:
    {{- include "learn-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: postgres
  password: {{ .Values.postgresql.cluster.superuserSecret.password | default (randAlphaNum 16) }}
{{- end }} 
