{{- if not (lookup "v1" "Secret" .Release.Namespace .Values.postgresql.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.existingSecret }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "learn-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.postgresql.cluster.bootstrap.initdb.owner | default "learn_platform" }}
  password: {{ randAlphaNum 16 | quote }}
  POSTGRES_DB: {{ .Values.postgresql.cluster.bootstrap.initdb.database | default "learn_platform" }}
  POSTGRES_USER: {{ .Values.postgresql.cluster.bootstrap.initdb.owner | default "learn_platform" }}
  POSTGRES_PASSWORD: {{ randAlphaNum 16 | quote }}
{{- end }}
