{{- if .Values.cloudnativepg.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgresql
  labels:
    {{- include "learn-platform.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: 5432
      protocol: TCP
      name: postgresql
  # This service is a proxy to the CloudNativePG read-write service
  # It provides backward compatibility for applications expecting a standard PostgreSQL service name
  selector:
    postgresql: {{ .Values.postgresql.cluster.name }}
    role: primary
{{- end }}
