apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: server
    instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: server
      instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: server
        instance: {{ .Release.Name }}
    spec:
      initContainers:
        - name: wait-for-db
          image: "postgres:15"
          command: ['sh', '-c', '
            for i in $(seq 1 60); do
              echo "Attempt $i: Checking PostgreSQL readiness..."
              if pg_isready -h {{ .Values.postgresql.cluster.name }}-rw -U {{ .Values.postgresql.cluster.bootstrap.initdb.owner }} -d {{ .Values.postgresql.cluster.bootstrap.initdb.database }}; then
                echo "PostgreSQL is ready!"
                exit 0
              fi
              echo "Waiting for PostgreSQL... (attempt $i/60)"
              sleep 5
            done
            echo "PostgreSQL not ready after 5 minutes"
            exit 1
          ']
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.cluster.name }}-app
                  key: password
        - name: init-permissions
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["sh", "-c"]
          args:
            - |
              mkdir -p /usr/src/app/node_modules/.prisma /usr/src/app/prisma/generated
              chmod -R 777 /usr/src/app/node_modules/.prisma /usr/src/app/prisma/generated
          volumeMounts:
            - name: prisma-data
              mountPath: /usr/src/app/node_modules/.prisma
            - name: prisma-generated
              mountPath: /usr/src/app/prisma/generated
        - name: run-migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh", "-c"]
          args:
            - |
              cd /usr/src/app/server
              mkdir -p /usr/src/app/node_modules/.prisma /usr/src/app/prisma/generated
              chmod -R 777 /usr/src/app/node_modules/.prisma /usr/src/app/prisma/generated
              bunx prisma generate
              export DATABASE_URL="postgresql://$(cat /secrets/username):$(cat /secrets/password)@{{ .Values.postgresql.cluster.name }}-rw.{{ .Release.Namespace }}.svc.cluster.local:5432/{{ .Values.postgresql.cluster.bootstrap.initdb.database }}"
              bunx prisma migrate deploy
          envFrom:
            - secretRef:
                name: {{ .Values.server.existingSecret }}
          volumeMounts:
            - name: prisma-data
              mountPath: /usr/src/app/node_modules/.prisma
            - name: prisma-generated
              mountPath: /usr/src/app/prisma/generated
            - name: db-secrets
              mountPath: /secrets
              readOnly: true
      containers:
        - name: server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              export DATABASE_URL="postgresql://$(cat /secrets/username):$(cat /secrets/password)@{{ .Values.postgresql.cluster.name }}-rw.{{ .Release.Namespace }}.svc.cluster.local:5432/{{ .Values.postgresql.cluster.bootstrap.initdb.database }}"
              cd /usr/src/app/server && bun start
          ports:
            - name: http
              containerPort: {{ .Values.server.port }}
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ .Values.server.existingSecret }}
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            {{ toYaml .Values.server.resources | nindent 12 }}
          volumeMounts:
            - name: prisma-data
              mountPath: /usr/src/app/node_modules/.prisma
            - name: prisma-generated
              mountPath: /usr/src/app/prisma/generated
            - name: db-secrets
              mountPath: /secrets
              readOnly: true
      volumes:
        - name: prisma-data
          emptyDir: {}
        - name: prisma-generated
          emptyDir: {}
        - name: db-secrets
          secret:
            secretName: {{ .Values.postgresql.cluster.name }}-app
