app:
  name: learn-platform
  replicas: 1

image:
  repository: ghcr.io/catalinpit/learn-platform
  tag: latest
  pullPolicy: Always

cloudnativepg:
  enabled: true

postgresql:
  cluster:
    name: "learn-platform-db"
    namespace: "learn-platform"
    instances: 1
    storage:
      size: 10Gi
    bootstrap:
      initdb:
        database: "learn_platform"
        owner: "learn_platform"
    postgresGUC:
      shared_buffers: "128MB"
      max_connections: "100"
    postgresql:
      version: "15"
    monitoring:
      enablePodMonitor: true
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        memory: "1Gi"
    superuserSecret:
      name: "learn-platform-db-superuser"
      password: "" # Leave empty to generate a random password
    enableSuperuserAccess: false

server:
  port: 9999
  service:
    type: ClusterIP
    port: 80
    targetPort: 9999
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  existingSecret: "learn-platform-env"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    # Uncomment if cert-manager is installed
    # cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: sf.catalins.tech
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: learn-tls
      hosts:
        - sf.catalins.tech

labels:
  app: learn-platform
