# Application configuration
app:
  name: learn-platform
  replicas: 1

# Docker image configuration
image:
  repository: ghcr.io/catalinpit/learn-platform
  tag: latest
  pullPolicy: Always

# CloudNativePG configuration
cloudnativepg:
  enabled: true

# PostgreSQL cluster configuration
postgresql:
  # Database credentials secret
  existingSecret: "postgresql-credentials"
  # CloudNativePG cluster configuration
  cluster:
    name: "learn-platform-db"
    namespace: "learn-platform"
    instances: 1
    storage:
      size: 10Gi
    bootstrap:
      initdb:
        database: "learn_platform"
        owner: "learn_platform"
        secret:
          name: "postgresql-credentials"
    postgresGUC:
      shared_buffers: "128MB"
      max_connections: "100"
    postgresql:
      version: "15"
    monitoring:
      enablePodMonitor: true
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        memory: "1Gi"
  # Service configuration for backward compatibility
  service:
    type: ClusterIP
    port: 5432

# Server configuration
server:
  port: 9999
  service:
    type: ClusterIP
    port: 80
    targetPort: 9999
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  # Reference existing secrets for environment variables
  existingSecret: "learn-platform-env"

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    # Uncomment the following line if you have cert-manager installed
    # cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: sf.catalins.tech
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: learn-tls
      hosts:
        - sf.catalins.tech

# Common labels
labels:
  app: learn-platform
