apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql
  labels:
    {{- include "learn-platform.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | b64enc }}
  POSTGRES_USER: {{ .Values.postgresql.username | b64enc }}
  POSTGRES_DB: {{ .Values.postgresql.database | b64enc }}
